using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace MikaSourceGen
{
    // [PacketHandler] -> 핸들러 등록 코드 (GeneratedHandlers.g.cs)
    // 트리거가 메서드라서 [PacketHandler]를 가진 프로젝트(서버/클라)에서만 생성된다.
    public sealed partial class PacketHandlerGenerator
    {
        // 핸들러 메서드 1개 -> (패킷 타입, Id, MethodRef)
        static HandlerInfo? ExtractHandler(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IMethodSymbol m) return null;
            if (m.Parameters.Length != 2 || !m.IsStatic) return null; // (MikaSession, IPacket), static

            var packetType = m.Parameters[1].Type;

            var pAttr = packetType.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == PacketAttr);

            if (pAttr is null || pAttr.ConstructorArguments.Length == 0) return null;

            return new HandlerInfo(
                PacketType: packetType.ToDisplayString(),
                IdRef: ResolveIdRef(pAttr.ConstructorArguments[0]),
                MethodRef: $"{m.ContainingType.ToDisplayString()}.{m.Name}");
        }

        static void EmitHandlers(SourceProductionContext spc, ImmutableArray<HandlerInfo> handlers)
        {
            if (handlers.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using MikaNetwork.Core.Network;");
            sb.AppendLine();
            sb.AppendLine("namespace MikaGenerated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedHandlers");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void RegisterAll(MikaPacketManager manager)");
            sb.AppendLine("        {");
            foreach (var h in handlers)
                sb.AppendLine($"            manager.Register<{h.PacketType}>((ushort){h.IdRef}, {h.MethodRef});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedHandlers.g.cs", sb.ToString());
        }

        // 증분 캐시를 위한 값 동등성 (record)
        private readonly record struct HandlerInfo(string PacketType, string IdRef, string MethodRef);
    }
}
