using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MikaSourceGen
{
    [Generator(LanguageNames.CSharp)]
    public sealed class PacketHandlerGenerator : IIncrementalGenerator
    {
        private const string HandlerAttr = "MikaProtocol.PacketHandlerAttribute";
        private const string PacketAttr = "MikaProtocol.PacketAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // [PacketHandler] 붙은 메서드 수집
            var handlers = context.SyntaxProvider.ForAttributeWithMetadataName(
                    HandlerAttr,
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, _) => Extract(ctx))
                .Where(static h => h is not null)
                .Select(static (h, _) => h!.Value);

            context.RegisterSourceOutput(handlers.Collect(), Emit);
        }

        // 핸들러 1개 -> (패킷 타입, Id, MethodRef) 추출
        static HandlerInfo? Extract(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IMethodSymbol m) return null;
            if (m.Parameters.Length != 2 || !m.IsStatic) return null; // (MikaSession, IPacket), static

            var packetType = m.Parameters[1].Type; // PacketType

            var pAttr = packetType.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == PacketAttr);

            if (pAttr is null || pAttr.ConstructorArguments.Length == 0) return null;

            var idConst = pAttr.ConstructorArguments[0]; // enum 상수
            var idName = (idConst.Type as INamedTypeSymbol)?.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(f => f.HasConstantValue && Equals(f.ConstantValue, idConst.Value))
                ?.Name;

            return new HandlerInfo(
                PacketType: packetType.ToDisplayString(), // MikaProtocol.C_EchoRequest
                IdRef: idName is null
                    ? idConst.Value!.ToString() // MikaProtocol.PacketId.C_EchoRequest
                    : $"{idConst.Type!.ToDisplayString()}.{idName}",
                MethodRef: $"{m.ContainingType.ToDisplayString()}.{m.Name}"); // MikaDummyServer.XXXHandler.Handle_XXX
        }

        static void Emit(SourceProductionContext spc, ImmutableArray<HandlerInfo> handlers)
        {
            if (handlers.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using MikaNetwork.Core.Network;");
            sb.AppendLine();
            sb.AppendLine("namespace MikaGenerated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedHandlers");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void RegisterAll(MikaPacketManager manager)");
            sb.AppendLine("        {");
            foreach (var h in handlers)
                sb.AppendLine($"            manager.Register<{h.PacketType}>((ushort){h.IdRef}, {h.MethodRef});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedHandlers.g.cs", sb.ToString());
        }

        // 증분 캐시를 위한 값 동등성 (record)
        private readonly record struct HandlerInfo(string PacketType, string IdRef, string MethodRef);
    }
}
